resources:
- name: git-codebase
  type: git
  source:
    uri: https://github.com/pkhamdee/xunit-tested-dotnetcore
    branch: master
- name: pcf
  type: cf
  source:
    api: https://api.sys.pcfgcp.pkhamdee.com
    skip_cert_check: true
    username: admin
    password: aW8GtEpkke-ZHd80CA4dHlckZh8Qdc0A
    organization: development
    space: test
jobs:
- name: aspnetcore-unit-tests
  plan:
    - get: git-codebase
      trigger: true
    - task: run-tests
      privileged: true
      config:
        platform: linux
        inputs:
        - name: git-codebase
        image_resource:
            type: docker-image
            source:
              repository: microsoft/aspnetcore-build
        run:
            path: sh
            args:
            - -exc
            - |
                cd ./git-codebase
                 
- name: deploy-to-prod
  plan:
    - get: git-codebase
      trigger: true
      passed: [aspnetcore-unit-tests]
    - put: pcf
      params:
        manifest: git-codebase/manifest.yml
