resources:
- name: git-codebase
  type: git
  source:
    uri: https://github.com/pkhamdee/xunit-tested-dotnetcore
    branch: master
- name: pcf
  type: cf
  source:
    api: https://api.sys.pcfgcp.pkhamdee.com
    skip_cert_check: true
    username: admin
    password: aW8GtEpkke-ZHd80CA4dHlckZh8Qdc0A
    organization: development
    space: test
jobs:
- name: deploy-to-pcf
  plan:
    - get: git-codebase
      trigger: true
    - put: pcf
      params:
        manifest: git-codebase/manifest.yml